# -*- coding: utf-8 -*-
from . import hr_leave
from . import res_users
from . import som_common_project
from . import project
from . import som_calendar_week
from . import analytic_account
from . import som_worked_week
from . import hr_attendance
from . import hr_attendance_report
from . import hr_employee
from . import hr_attendance_overtime
from . import ir_ui_menu
from . import project_task
from . import hr_contract
from . import hr_apparisal
from . import survey_user
from . import hr_appraisal_survey
from . import res_company
from . import res_config_settings
from . import hr_leave_stress_day
from . import hr_holidays_public
from . import hr_leave_type
from . import helpdesk_ticket_team
from . import mail_thread
from . import mail_mail
